version: '3.7'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    ports:
      - 5432:5432

  app:
    build: .
    depends_on:
      - postgres
    restart: always
    ports:
      - 3000:3000
      - 80:3000
