version: '3.7'

services:
  postgres-test:
    image: 'postgres:10.7'
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    ports:
      - 54320:5432
